#!/bin/bash
#define version
version="kinectic"
#next update if less


#***脚本要在sudo下

sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
echo "                      导入源sucess" && echo "    import key"

#翻牆有可能識別不了下載失敗
sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
echo "                   ******key Update done then apt update"
sudo apt-get update && echo "                   *****update更新ubuntu"

#-f会出错

sudo apt-get -y install ros-${version}-desktop-full
sudo apt-get -f
echo "done"	&&	echo "                  ****初始化更新"


sudo rosdep init
rosdep update
echo "			****初始化更新done"&& echo "			***source"


echo "source /opt/ros/${version}/setup.bash" >> ~/.bashrc
echo "			************done"


echo "			****source"
source ~/.bashrc
echo "			***done"

echo "			****source /opt/ros/${version}/setup.bash"
source /opt/ros/${version}/setup.bash

#-y自&&动确认
echo "			****sudo apt-get install python-rosinstall"
sudo apt-get -y install python-rosinstall && source ~/.bashrc




echo "			****export | grep ROS"
export | grep ROS

echo "			***mkdir -p ~/catkin_ws/src&&cd ~/catkin_ws/src&&cd ~/catkin_ws/&&catkin_make"
mkdir -p ~/catkin_ws/src
cd ~/catkin_ws/src
cd ~/catkin_ws/
catkin_make


echo "			***source devel/setup.bash"
source ~/catkin_ws/devel/setup.bash

echo "			***echo $ROS_PACKAGE_PATH"
echo $ROS_PACKAGE_PATH
